---
- hosts: docker
 
  tasks:
  - name: stop existing Container on docker host
    command: docker stop linkfireapp-container
    ignore_errors: yes

 - name: remove the Container on docker host
    command: docker rm linkfireapp-container
    ignore_errors: yes

 - name: remove image on docker host
    command: docker rmi nageshgadupudi1aws/linkfireapp:latest
    ignore_errors: yes

 - name: create Container on docker host
    command: docker run -d --name linkfireapp-container -p 8082:8080 nageshgadupudi1aws/linkfireapp:latest
